# -*- coding: utf-8 -*-
"""day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFYS4caSEMm0goxphqFmqO1cGWNFV1F_

input and output methods
"""

name  = input("enter your name: ") #
print(f"Welcome, {name}!")

age = int(input("Enter your age: "))
type(age)
# <class 'str'>

# convert for math operation
num = int(input("Enter a number: "))
print(num * 2)

# printing  in different ways
print("Hello, Datasprint 30!")

print("Python","SQL","Power BI", sep="| ")

print("name:","Prathibha","| Age:", 25)

print("Hello", end=" ")
print("World !")

"""membership operator (in/not in)

"""

fruits = ["apple","banana","cherry"]
"banana" in fruits

fruits = ["apple","banana","cherry"]
"mango" not in fruits

"""Identity operators(is /is not)"""

#Is checks  if two variables point to the same object in memory
#Different  from == which checks value equality.
a = [1, 2, 3]
b = [1, 2, 3]
c=a
a==b # same value

a is b # same object?
a is c # c points to same object as a
print(id(a),id(b),id(c))

"""Assignment operator"""

x = 10
print(x)

x += 5
print(x)

x -=3
print(x)

x *=2
print(x)

x/=4
print(x)

x **= 3
print(x)

"""Logical operator"""

#Logical operator
# and both must be true
# or at least one must be true
#not inverts True/False
a,b = True,False
a and b

age = 25
has_id = True
age>=18 and has_id

a, b = True, False
print(a or b)

# Practical example
has_ticket = False
has_voucher = True

# You can enter if you have a ticket OR a voucher
can_enter = has_ticket or has_voucher
print(f"Can enter: {can_enter}")

a = True
b = False

print(f"not a: {not a}") # Inverts True to False
print(f"not b: {not b}") # Inverts False to True

# Practical example
is_logged_in = False
'''The syntax you've shared is a perfect example of using the not operator.
While or checks if either condition is true, not simply flips the result:
it turns True into False and False into True.'''
if not is_logged_in:
    print("Please log in to access this feature.")

"""comparsion operator"""

x, y = 10, 20
x==y

x, y = 10, 20
x !=y

x, y = 10, 20
x > y

x, y = 10,20
x < y

x = 10
x>=10

x=15
x<=10

"""Modulus%(remainder) Exponentation**(power)

"""

10 % 3

15 % 4

2 ** 5

"""Multiplication & Division"""

3*4

"Ha"*3

"""Floor division"""

7/2 # always return to float

7//2 # truncate integer

-7 //2 # Floors towards negative infitify

"""Addition  & substraction"""

2+7

x = 10
x + 5

"Hello"+" "+"world!"

10 -3

a , b = 15, 4
a - b

"""Dynamic typing"""

x = 10
type(x)
< class 'int'>

age = 25
print(type(age))
# Output: <class 'int'>

x = "hello"
type(x)

x = 3.14
print(type(float(x)))

"""Multiple assignment"""

a, b, c = 10, 20,30
print (a,b,c)

x= y= z= 100
print(x, y, z)# same value to multiple vars

"""  Data type"""

age = 35
print(type(age))

height= 9.5
print(type(height))

is_student =True
print(type(is_student))

student = "Prathibha"
print(type(student))

marks_scored_80 = True
print(type("marks"))

user_email = None
print(type(user_email))

"""Valid & Invalid

"""

# Variable name
x1 = 10
student_age = 21
print(x1, student_age)

# Invalid name
1x = 5
if = 3

# creating of variables
age = 25
print(age)

"""Variable"""

name = "DataSprint"
is_enrolled = True
age = 30
print(name, is_enrolled, age)

print("Hello, DataSprint  30!")

